
package view;


import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import javax.swing.JOptionPane;


public class General extends javax.swing.JFrame {


    public General() {
        initComponents();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btn_kbyt = new javax.swing.JButton();
        btn_test = new javax.swing.JButton();
        btn_ttcly = new javax.swing.JButton();
        btn_tke = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();

        jButton1.setText("jButton1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jButton3.setText("jButton3");

        jLabel5.setText("jLabel5");

        jButton4.setText("jButton4");

        jButton5.setText("jButton5");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));
        jPanel1.setForeground(new java.awt.Color(102, 255, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_kbyt.setBackground(new java.awt.Color(204, 102, 255));
        btn_kbyt.setText("Khai báo y tế  ");
        btn_kbyt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kbytActionPerformed(evt);
            }
        });
        jPanel1.add(btn_kbyt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 114, 30));

        btn_test.setBackground(new java.awt.Color(204, 102, 255));
        btn_test.setText("Thông tin test covid");
        btn_test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_testActionPerformed(evt);
            }
        });
        jPanel1.add(btn_test, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 293, 114, 30));

        btn_ttcly.setBackground(new java.awt.Color(204, 102, 255));
        btn_ttcly.setForeground(new java.awt.Color(102, 102, 102));
        btn_ttcly.setText("thong tin cách ly");
        btn_ttcly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ttclyActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ttcly, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 293, 114, 30));

        btn_tke.setBackground(new java.awt.Color(204, 102, 255));
        btn_tke.setText("Thống kê");
        btn_tke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tkeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_tke, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 353, 114, 30));

        jButton2.setBackground(new java.awt.Color(255, 153, 255));
        jButton2.setText("Đăng xuất");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pic2.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 440));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kbytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kbytActionPerformed
        // TODO add your handling code here:
         tt_khaibao kb;
        
            kb = new tt_khaibao();
             kb.setVisible(true);
         
            
    }//GEN-LAST:event_btn_kbytActionPerformed

    private void btn_testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_testActionPerformed
        // TODO add your handling code here:
        new tt_testCovid().setVisible(true);
        
    }//GEN-LAST:event_btn_testActionPerformed

    private void btn_ttclyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ttclyActionPerformed
        // TODO add your handling code here:
           tt_cly cly;
            cly = new tt_cly();
            cly.setVisible(true);
        
    }//GEN-LAST:event_btn_ttclyActionPerformed

    private void btn_tkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tkeActionPerformed
        // TODO add your handling code here:
        new ThongKe().setVisible(true);
    }//GEN-LAST:event_btn_tkeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       if( JOptionPane.showConfirmDialog(null, "Can you exit ?","Confirm",
               JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            new login().setVisible(true);
       }
    }//GEN-LAST:event_jButton2ActionPerformed

  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new General().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kbyt;
    private javax.swing.JButton btn_test;
    private javax.swing.JButton btn_tke;
    private javax.swing.JButton btn_ttcly;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
